# Jekyll config for CritiPicks.com
# based on the Agency theme

url: "https://www.critipicks.com"

title: CritiPicks
email: contact@critipicks.com
description: CritiPicks Product Recommendations
author: The CritiPicks Team

collections:
  reviews:
    output: true
    permalink: /review/:title/
  lists:
    output: true
    permalink: /list/:title/

defaults:
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "review"
